name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/TinyInst/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/TinyInst/build
        run: cmake ..

      - name: Build
        working-directory: ${{runner.workspace}}/TinyInst/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/TinyInst/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C Release
